name = "lean_matrix_sos"
version = "0.1.1"
keywords = ["math", "lean", "sos", "matrix-polynomials"]
defaultTargets = ["MatrixSOS"]
fixedToolchain = true

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
linter.style.longLine = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0"

[[lean_lib]]
name = "MatrixSOS"
